name: "Check Pull Request"
on:
  pull_request:
    branches: ["**"]
  push:
    branches:
      - master
jobs:
  check_pr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: ["check:lint", "check:types"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ${{ matrix.step }}
        run: npm install && npm run ${{ matrix.step }}
