name: release-headless

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 20
      - name: Create headless release artifact
        id: create_headless_release
        run: |
          npm install
          npm run build:headless
          zip -r headless.zip ./renderer/dist-headless
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "headless.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
