name: release-headless

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 20
      - name: Build/release Electron app
        run: |
          npm install
          npm run build
      - name: Create headless release artifact
        if: matrix.os == 'ubuntu-latest'
        id: create_headless_release
        run: |
          npm run build:headless
          zip -r headless.zip ./renderer/dist-headless
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "headless.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          replacesArtifacts: true
